name: Testing
on:
  - pull_request

jobs:
  # Skip while developing integ tests.
  # unit-tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Install Go
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: 1.21.x
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Test
  #       run: make test
        
  integration-tests:
    #needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      # Setup kind cluster
      - uses: engineerd/setup-kind@v0.5.0
        with:
          wait: 300s
          version: v0.14.0
          image: kindest/node:v1.26.14

      # Setup Go
      - uses: actions/setup-go@v2
        with:
          go-version: '1.21'

      #  Run tests
      - name: E2E Tests
        run: make test-e2e
        env:
          TEST_USE_EXISTING_CLUSTER: "true"
          WATCH_NAMESPACE: ""
          OPERATOR_NAME: "podinfo"
